// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, owner string, balance int64, currency string) (Account, error)
	DeleteAccount(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	ListAccounts(ctx context.Context, limit int32, offset int32) ([]Account, error)
	UpdateAccount(ctx context.Context, iD int64, balance int64) (Account, error)
}

var _ Querier = (*Queries)(nil)
